import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../../../constants/colors";
import { RADIUS, SPACING } from "../../../constants/spacing";

export const addShoppingItemScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.surface,
  },
  title: {
    fontSize: 20,
    fontWeight: "800",
    color: COLORS.onSurface,
  },
  doneText: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.primary,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surfaceContainer,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: Platform.OS === "ios" ? 10 : 6,
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
  },
  searchIcon: {
    marginRight: SPACING.sm,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: COLORS.onSurface,
  },
  chipList: {
    flexGrow: 0,
    marginBottom: SPACING.lg,
  },
  chipListContent: {
    paddingHorizontal: SPACING.lg,
    gap: SPACING.sm,
  },
  scrollContent: {
    paddingHorizontal: SPACING.lg,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SPACING.md,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.onSurface,
  },
  seeAllText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.primary,
  },
  horizontalList: {
    marginBottom: SPACING.xl,
  },
  horizontalListContent: {
    gap: SPACING.md,
    paddingBottom: 4,
  },
  suggestionCard: {
    width: 156,
    backgroundColor: COLORS.surfaceContainerLowest,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.surfaceContainerHigh,
    overflow: "hidden",
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  cardImage: {
    width: "100%",
    height: 110,
    backgroundColor: COLORS.surfaceContainer,
  },
  cardBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: RADIUS.sm,
  },
  cardBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#ffffff",
  },
  cardInfo: {
    padding: SPACING.md,
  },
  itemName: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.onSurface,
    marginBottom: 2,
  },
  itemQty: {
    fontSize: 12,
    color: COLORS.onSurfaceVariant,
    marginBottom: SPACING.md,
  },
  addBtn: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.primary,
    paddingVertical: 8,
    borderRadius: RADIUS.sm,
    gap: 4,
  },
  addBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#ffffff",
  },
  popularHeader: {
    marginBottom: SPACING.md,
  },
  popularList: {
    gap: SPACING.md,
  },
  popularItemRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.surfaceContainerLowest,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.surfaceContainerHigh,
  },
  popularItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    flex: 1,
  },
  popularItemImage: {
    width: 56,
    height: 56,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.surfaceContainer,
  },
  popularItemInfo: {
    justifyContent: "center",
    flex: 1,
  },
  popularItemName: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.onSurface,
    marginBottom: 2,
  },
  popularItemQty: {
    fontSize: 12,
    color: COLORS.onSurfaceVariant,
  },
  circleActionBtn: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.full,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    backgroundColor: COLORS.surfaceContainerLowest,
  },
  circleActionBtnActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  floatingBanner: {
    position: "absolute",
    left: SPACING.lg,
    right: SPACING.lg,
    backgroundColor: "#1c1b1b",
    borderRadius: RADIUS.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  bannerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    flex: 1,
  },
  bannerBadgeCircle: {
    width: 28,
    height: 28,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primaryContainer,
    alignItems: "center",
    justifyContent: "center",
  },
  bannerBadgeCircleText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 14,
  },
  bannerTextContainer: {
    flex: 1,
  },
  bannerTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  bannerSub: {
    color: "#a4b1ab",
    fontSize: 11,
    marginTop: 1,
  },
  bannerConfirmBtn: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm + 2,
    borderRadius: RADIUS.sm,
  },
  bannerConfirmBtnText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 14,
  },
});
