import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../../../constants/colors";
import { RADIUS, SPACING } from "../../../constants/spacing";

export const shoppingScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.xl,
  },
  titleContainer: {
    marginBottom: SPACING.lg,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: COLORS.onSurface,
    letterSpacing: 0,
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.onSurfaceVariant,
    marginTop: 4,
    opacity: 0.85,
  },
  bannerButton: {
    marginBottom: SPACING.xl,
  },
  banner: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
    paddingHorizontal: 18,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  bannerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    flex: 1,
  },
  bannerText: {
    color: COLORS.onPrimary,
    fontSize: 15,
    fontWeight: "700",
    flex: 1,
  },
  statRow: {
    flexDirection: "row",
    gap: SPACING.md,
    marginBottom: SPACING.lg,
  },
  statPill: {
    flex: 1,
    minHeight: 70,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    backgroundColor: COLORS.surfaceContainerLowest,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  statValue: {
    color: COLORS.primary,
    fontSize: 22,
    fontWeight: "900",
  },
  statLabel: {
    color: COLORS.onSurfaceVariant,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  errorBanner: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#f0b8ad",
    backgroundColor: "#fff0ed",
    paddingHorizontal: 12,
    marginBottom: SPACING.lg,
  },
  errorText: {
    flex: 1,
    color: "#9c3b2c",
    fontSize: 13,
    fontWeight: "800",
  },
  loadingBlock: {
    minHeight: 180,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    color: COLORS.onSurfaceVariant,
    fontSize: 13,
    fontWeight: "700",
    marginTop: 10,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    backgroundColor: COLORS.surfaceContainerLowest,
    padding: 22,
    minHeight: 210,
  },
  emptyIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: COLORS.surfaceContainer,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  emptyTitle: {
    color: COLORS.onSurface,
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 5,
    textAlign: "center",
  },
  emptyText: {
    color: COLORS.onSurfaceVariant,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
    textAlign: "center",
  },
  section: {
    marginBottom: SPACING.xl,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.md,
  },
  sectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.onSurface,
  },
  badge: {
    backgroundColor: COLORS.surfaceContainer,
    paddingHorizontal: SPACING.md,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.onSurfaceVariant,
    opacity: 0.8,
  },
  card: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "rgba(189, 202, 191, 0.3)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(189, 202, 191, 0.15)",
  },
  itemRowLast: {
    borderBottomWidth: 0,
  },
  checkbox: {
    marginRight: 14,
  },
  itemContent: {
    flex: 1,
  },
  itemName: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.onSurface,
  },
  itemNameChecked: {
    color: COLORS.onSurfaceVariant,
    textDecorationLine: "line-through",
    opacity: 0.6,
  },
  itemSubtext: {
    fontSize: 13,
    color: COLORS.onSurfaceVariant,
    marginTop: 2,
    opacity: 0.8,
  },
  fab: {
    position: "absolute",
    right: SPACING.lg,
    bottom: SPACING.lg,
    width: 56,
    height: 56,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.primary,
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
});
