import { StyleSheet } from "react-native";
import { COLORS } from "../../../constants/colors";
import { RADIUS, SPACING } from "../../../constants/spacing";

export const shoppingScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.xl,
  },
  titleContainer: {
    marginBottom: SPACING.lg,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: COLORS.onSurface,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.onSurfaceVariant,
    marginTop: 4,
    opacity: 0.85,
  },
  bannerButton: {
    marginBottom: SPACING.xl,
  },
  banner: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
    paddingHorizontal: 18,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  bannerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    flex: 1,
  },
  bannerText: {
    color: COLORS.onPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
  addIngredientButton: {
    minHeight: 52,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.primary + "45",
    backgroundColor: COLORS.surfaceContainerLowest,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
    marginBottom: SPACING.xl,
  },
  addIngredientButtonText: {
    color: COLORS.primary,
    fontSize: 15,
    fontWeight: "700",
  },
  section: {
    marginBottom: SPACING.xl,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.md,
  },
  sectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.onSurface,
  },
  badge: {
    backgroundColor: COLORS.surfaceContainer,
    paddingHorizontal: SPACING.md,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.onSurfaceVariant,
    opacity: 0.8,
  },
  card: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "rgba(189, 202, 191, 0.3)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  swipeRow: {
    position: "relative",
    overflow: "hidden",
    backgroundColor: COLORS.error,
  },
  deleteAction: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 82,
    backgroundColor: COLORS.error,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  deleteActionText: {
    color: COLORS.onPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(189, 202, 191, 0.15)",
    backgroundColor: COLORS.surfaceContainerLowest,
  },
  itemRowLast: {
    borderBottomWidth: 0,
  },
  checkbox: {
    marginRight: 14,
  },
  itemContent: {
    flex: 1,
  },
  itemName: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.onSurface,
  },
  itemNameChecked: {
    color: COLORS.onSurfaceVariant,
    textDecorationLine: "line-through",
    opacity: 0.6,
  },
  itemSubtext: {
    fontSize: 13,
    color: COLORS.onSurfaceVariant,
    marginTop: 2,
    opacity: 0.8,
  },
  addForm: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "rgba(189, 202, 191, 0.35)",
    padding: SPACING.lg,
    marginBottom: SPACING.xl,
  },
  addFormTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.onSurface,
    marginBottom: SPACING.md,
  },
  input: {
    minHeight: 46,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.md,
    color: COLORS.onSurface,
    fontSize: 14,
    marginBottom: SPACING.md,
  },
  formRow: {
    flexDirection: "row",
    gap: SPACING.md,
  },
  quantityInput: {
    flex: 1,
  },
  unitInput: {
    flex: 1,
  },
  addButton: {
    height: 48,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  addButtonText: {
    color: COLORS.onPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  cancelEditButton: {
    height: 44,
    borderRadius: RADIUS.full,
    alignItems: "center",
    justifyContent: "center",
    marginTop: SPACING.sm,
  },
  cancelEditButtonText: {
    color: COLORS.onSurfaceVariant,
    fontSize: 14,
    fontWeight: "700",
  },
  disabled: {
    opacity: 0.65,
  },
  loader: {
    marginTop: SPACING.xxl,
  },
  emptyAddContainer: {
    minHeight: 360,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyAddOnlyButton: {
    height: 52,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: SPACING.sm,
    paddingHorizontal: SPACING.xl,
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  emptyAddOnlyButtonText: {
    color: COLORS.onPrimary,
    fontSize: 16,
    fontWeight: "700",
  },
  emptyState: {
    alignItems: "center",
    backgroundColor: COLORS.surfaceContainerLowest,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "rgba(189, 202, 191, 0.35)",
    padding: SPACING.xl,
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: COLORS.onSurface,
    marginTop: SPACING.md,
  },
  emptyText: {
    fontSize: 14,
    color: COLORS.onSurfaceVariant,
    lineHeight: 20,
    marginTop: SPACING.sm,
    textAlign: "center",
  },
  emptyAddButton: {
    height: 44,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: SPACING.sm,
    paddingHorizontal: SPACING.lg,
    marginTop: SPACING.lg,
  },
  emptyAddButtonText: {
    color: COLORS.onPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  fab: {
    position: "absolute",
    right: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
});
