import { StyleSheet } from "react-native";

import { COLORS } from "../../../constants/colors";
import { SPACING } from "../../../constants/spacing";

export const plannerStyles = StyleSheet.create({
  scrollContent: {
    paddingHorizontal: SPACING.lg,
    paddingTop: 18,
  },
  hero: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    padding: 16,
    marginBottom: 18,
  },
  heroHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  eyebrow: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 3,
  },
  heroTitle: {
    color: COLORS.onSurface,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
  },
  heroStats: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  miniStat: {
    minWidth: "23%",
    flex: 1,
    backgroundColor: COLORS.surfaceContainer,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  miniStatValue: {
    color: COLORS.onSurface,
    fontSize: 18,
    fontWeight: "900",
  },
  miniStatLabel: {
    color: COLORS.onSurfaceVariant,
    fontSize: 11,
    fontWeight: "700",
    marginTop: 2,
  },
  workspaceSwitch: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 14,
  },
  section: {
    marginBottom: 20,
  },
  sectionHeader: {
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "900",
    color: COLORS.onSurface,
  },
  sectionSubtitle: {
    marginTop: 4,
    color: COLORS.onSurfaceVariant,
    fontSize: 13,
    lineHeight: 19,
  },
  formGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  field: {
    flex: 1,
    minWidth: 144,
  },
  fieldLabel: {
    color: COLORS.onSurfaceVariant,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 5,
  },
  input: {
    minHeight: 46,
    backgroundColor: COLORS.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    color: COLORS.onSurface,
    fontSize: 14,
    marginBottom: 10,
  },
  textArea: {
    minHeight: 76,
    textAlignVertical: "top",
  },
  inputWithButton: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  inputGrow: {
    flex: 1,
  },
  squareButton: {
    width: 46,
    height: 46,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.primary,
    marginBottom: 10,
  },
  segmentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  chip: {
    minHeight: 36,
    borderRadius: 999,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    backgroundColor: COLORS.surfaceContainer,
  },
  chipActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  chipText: {
    color: COLORS.onSurfaceVariant,
    fontWeight: "800",
    fontSize: 13,
  },
  chipTextActive: {
    color: COLORS.onPrimary,
  },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 2,
    marginBottom: 10,
  },
  button: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 8,
    paddingHorizontal: 14,
    backgroundColor: COLORS.primary,
  },
  secondaryButton: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
  },
  disabledButton: {
    opacity: 0.55,
  },
  buttonText: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.onPrimary,
  },
  secondaryButtonText: {
    color: COLORS.primary,
  },
  inlineNotice: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    borderRadius: 8,
    padding: 12,
    backgroundColor: "#e7f5ee",
    borderWidth: 1,
    borderColor: "#b7dccb",
  },
  inlineNoticeText: {
    flex: 1,
    color: COLORS.onSurface,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  bucket: {
    marginBottom: 12,
  },
  bucketHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  bucketTitle: {
    color: COLORS.onSurface,
    fontSize: 15,
    fontWeight: "900",
  },
  bucketCount: {
    color: COLORS.primary,
    fontWeight: "900",
  },
  bucketWarning: {
    color: COLORS.tertiary,
  },
  foodStrip: {
    gap: 8,
  },
  foodPill: {
    width: 148,
    minHeight: 70,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    backgroundColor: COLORS.surfaceContainerLowest,
    padding: 10,
    justifyContent: "center",
  },
  foodName: {
    color: COLORS.onSurface,
    fontWeight: "900",
    fontSize: 14,
    marginBottom: 4,
  },
  foodMeta: {
    color: COLORS.onSurfaceVariant,
    fontWeight: "700",
    fontSize: 12,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  metric: {
    width: "48%",
    minHeight: 72,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    backgroundColor: COLORS.surfaceContainerLowest,
    padding: 12,
    justifyContent: "center",
  },
  metricValue: {
    fontSize: 17,
    fontWeight: "900",
    color: COLORS.primary,
    marginBottom: 3,
  },
  metricLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.onSurfaceVariant,
  },
  extractionBox: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    backgroundColor: COLORS.surfaceContainerLowest,
    padding: 12,
  },
  extractionTitle: {
    color: COLORS.onSurface,
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 3,
  },
  extractionMeta: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 8,
  },
  extractionIngredient: {
    color: COLORS.onSurfaceVariant,
    fontSize: 13,
    lineHeight: 19,
  },
  adminTabs: {
    gap: 8,
  },
  dataRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    backgroundColor: COLORS.surfaceContainerLowest,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  dataText: {
    flex: 1,
  },
  dataTitle: {
    color: COLORS.onSurface,
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 2,
  },
  dataSubtitle: {
    color: COLORS.onSurfaceVariant,
    fontSize: 12,
    lineHeight: 17,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surfaceContainer,
    marginLeft: 8,
  },
  reviewItem: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    backgroundColor: COLORS.surfaceContainerLowest,
    padding: 12,
    marginBottom: 12,
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  reviewType: {
    color: COLORS.primary,
    fontSize: 13,
    fontWeight: "900",
  },
  reviewStatus: {
    color: COLORS.onSurfaceVariant,
    fontSize: 12,
    fontWeight: "800",
  },
  reviewContent: {
    color: COLORS.onSurfaceVariant,
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 10,
  },
  detailTabPanel: {
    marginBottom: 20,
  },
  detailTabScroll: {
    marginBottom: 12,
  },
  detailTabContent: {
    flexDirection: "row",
    gap: 8,
    paddingRight: SPACING.lg,
  },
  hint: {
    color: COLORS.primary,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 10,
  },
  emptyText: {
    color: COLORS.onSurfaceVariant,
    fontSize: 14,
    lineHeight: 21,
  },
  loader: {
    marginVertical: 20,
  },
  savingOverlay: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 14,
  },
  savingText: {
    color: COLORS.onSurfaceVariant,
    fontWeight: "700",
  },
});
