import { StyleSheet } from "react-native";

import { COLORS } from "../../../constants/colors";
import { RADIUS, SPACING } from "../../../constants/spacing";

export const familyCloudStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: {
    alignItems: "center",
    borderBottomColor: COLORS.outlineVariant + "70",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
  },
  iconButton: {
    alignItems: "center",
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  title: { color: COLORS.onSurface, fontSize: 18, fontWeight: "700" },
  content: { gap: SPACING.lg, padding: SPACING.lg, paddingBottom: SPACING.xxl },
  formBox: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderColor: COLORS.outlineVariant + "45",
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    padding: SPACING.lg,
  },
  sectionTitle: {
    color: COLORS.onSurfaceVariant,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.7,
    marginBottom: SPACING.md,
    textTransform: "uppercase",
  },
  inputRow: { flexDirection: "row", gap: SPACING.sm },
  input: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.outlineVariant,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    color: COLORS.onSurface,
    flex: 1,
    fontSize: 14,
    minHeight: 46,
    paddingHorizontal: SPACING.md,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.md,
    justifyContent: "center",
    minHeight: 46,
    paddingHorizontal: SPACING.lg,
  },
  fullButton: {
    alignItems: "center",
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.full,
    height: 48,
    justifyContent: "center",
    marginTop: SPACING.md,
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: COLORS.outlineVariant,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    flex: 1,
    height: 44,
    justifyContent: "center",
  },
  acceptButton: {
    alignItems: "center",
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.full,
    flex: 1,
    height: 44,
    justifyContent: "center",
  },
  primaryButtonText: { color: COLORS.onPrimary, fontSize: 14, fontWeight: "700" },
  secondaryButtonText: { color: COLORS.onSurface, fontSize: 14, fontWeight: "700" },
  disabled: { opacity: 0.65 },
  loader: { marginVertical: SPACING.xl },
  emptyBox: {
    alignItems: "center",
    backgroundColor: COLORS.surfaceContainerLowest,
    borderColor: COLORS.outlineVariant + "45",
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    padding: SPACING.xl,
  },
  emptyTitle: { color: COLORS.onSurface, fontSize: 17, fontWeight: "700", marginTop: SPACING.md },
  emptyText: {
    color: COLORS.onSurfaceVariant,
    fontSize: 14,
    lineHeight: 20,
    marginTop: SPACING.sm,
    textAlign: "center",
  },
  householdRow: { flexDirection: "row", gap: SPACING.sm, paddingRight: SPACING.lg },
  householdChip: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderColor: COLORS.outlineVariant,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    minWidth: 150,
    padding: SPACING.md,
  },
  householdChipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  householdName: { color: COLORS.onSurface, fontSize: 15, fontWeight: "700" },
  householdNameActive: { color: COLORS.onPrimary },
  householdRole: { color: COLORS.onSurfaceVariant, fontSize: 12, marginTop: SPACING.xs },
  householdRoleActive: { color: COLORS.onPrimaryContainer },
  roleRow: { flexDirection: "row", gap: SPACING.sm, marginTop: SPACING.md },
  roleChip: {
    borderColor: COLORS.outlineVariant,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
  },
  roleChipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  roleText: { color: COLORS.onSurfaceVariant, fontSize: 13, fontWeight: "700" },
  roleTextActive: { color: COLORS.onPrimary },
  memberCard: {
    alignItems: "center",
    backgroundColor: COLORS.surfaceContainerLowest,
    borderColor: COLORS.outlineVariant + "45",
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    flexDirection: "row",
    marginBottom: SPACING.sm,
    padding: SPACING.md,
  },
  avatar: {
    alignItems: "center",
    backgroundColor: COLORS.primary + "20",
    borderRadius: RADIUS.full,
    height: 44,
    justifyContent: "center",
    marginRight: SPACING.md,
    width: 44,
  },
  avatarText: { color: COLORS.primary, fontSize: 17, fontWeight: "800" },
  memberInfo: { flex: 1 },
  memberName: { color: COLORS.onSurface, fontSize: 15, fontWeight: "700" },
  memberEmail: { color: COLORS.onSurfaceVariant, fontSize: 13, marginTop: 2 },
  memberRole: { color: COLORS.primary, fontSize: 12, fontWeight: "700", marginTop: SPACING.xs },
  invitationCard: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderColor: COLORS.outlineVariant + "45",
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    marginBottom: SPACING.sm,
    padding: SPACING.md,
  },
  invitationHeader: { alignItems: "center", flexDirection: "row" },
  invitationActionRow: { flexDirection: "row", gap: SPACING.sm, marginTop: SPACING.md },
  invitationEmptyBox: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderColor: COLORS.outlineVariant + "45",
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    padding: SPACING.md,
  },
  invitationEmptyText: { color: COLORS.onSurfaceVariant, fontSize: 13, textAlign: "center" },
  memberActions: { flexDirection: "row", gap: SPACING.xs },
  actionButton: {
    alignItems: "center",
    borderColor: COLORS.outlineVariant + "70",
    borderRadius: RADIUS.full,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
});
