import { StyleSheet } from "react-native";
import { COLORS } from "../../../constants/colors";
import { SPACING, RADIUS } from "../../../constants/spacing";

export const scannerScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  cameraContainer: {
    flex: 1,
    backgroundColor: "#1a1a1a",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  cameraPlaceholder: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#2a3d35",
  },
  scanFrame: {
    width: 250,
    height: 250,
    borderWidth: 2,
    borderColor: COLORS.primary,
    borderRadius: RADIUS.lg,
    position: "absolute",
  },
  detectionLabel: {
    position: "absolute",
    top: SPACING.lg,
    left: SPACING.lg,
    backgroundColor: COLORS.primary,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.full,
    flexDirection: "row",
    alignItems: "center",
  },
  detectionText: {
    color: COLORS.onPrimary,
    fontWeight: "600",
    marginLeft: SPACING.sm,
    fontSize: 14,
  },
  resultSection: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.xl,
    minHeight: 450,
  },
  resultHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: SPACING.lg,
  },
  resultIconContainer: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    marginRight: SPACING.md,
  },
  resultTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.onSurface,
  },
  productName: {
    fontSize: 28,
    fontWeight: "bold",
    color: COLORS.onSurface,
    marginBottom: SPACING.sm,
  },
  aiPrediction: {
    fontSize: 16,
    color: COLORS.onSurfaceVariant,
    marginBottom: SPACING.lg,
  },
  aiDays: {
    color: COLORS.primary,
    fontWeight: "bold",
  },
  section: {
    marginBottom: SPACING.xl,
  },
  sectionLabel: {
    fontSize: 14,
    color: COLORS.onSurfaceVariant,
    marginBottom: SPACING.md,
  },
  quantityControl: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surfaceContainer,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    alignSelf: "flex-start",
  },
  quantityButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  quantityButtonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  quantityValue: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.onSurface,
    marginHorizontal: SPACING.md,
  },
  storageDropdown: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.surfaceContainer,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    marginBottom: SPACING.lg,
  },
  storageLabel: {
    fontSize: 16,
    color: COLORS.onSurface,
    flex: 1,
  },
  datePickerRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surfaceContainer,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
  },
  dateLabel: {
    fontSize: 16,
    color: COLORS.onSurface,
    flex: 1,
  },
  dateValue: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.primary,
  },
  buttonRow: {
    flexDirection: "row",
    gap: SPACING.md,
    marginTop: SPACING.xl,
  },
  button: {
    flex: 1,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    justifyContent: "center",
    alignItems: "center",
  },
  secondaryButton: {
    backgroundColor: COLORS.surfaceContainer,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
  },
  secondaryButtonText: {
    color: COLORS.onSurface,
    fontWeight: "600",
    fontSize: 16,
  },
  primaryButton: {
    backgroundColor: COLORS.primary,
  },
  primaryButtonText: {
    color: COLORS.onPrimary,
    fontWeight: "600",
    fontSize: 16,
  },
  barcodeIcon: {
    width: 28,
    height: 28,
    backgroundColor: COLORS.surfaceContainer,
    borderRadius: RADIUS.md,
    justifyContent: "center",
    alignItems: "center",
  },
  captureButton: {
    position: "absolute",
    bottom: SPACING.xl,
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  captureButtonInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: COLORS.onPrimary,
  },
});
